language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules
before_install:
  - pip install --user codecov
script:
  - yarn run validate
  - yarn run test:cov
  - yarn run build
after_success:
  - codecov --file coverage/lcov.info --disable search
